library(tidyverse)
library(readr)
climate_raw<-readr::read_csv("data-raw/climate.csv")
View(climate_raw)
library(dplyr)
climate_n<-climate_raw%>%select(1:9)
View(climate_n)
usethis::use_data(climate_n, overwrite = TRUE)
devtools::load_all()
